channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.11,<4
  - pip
  - nextflow
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - pytest
  - altair
  - click
  - jinja2
  - psutil
  - csvtk
  - curl
  - biopython=1.85
