channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cairo=1.18.4
  - coreutils=9.5
  - csvtk=0.34.0
  - curl=8.14.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - giflib=5.2.2
  - graphite2=1.3.14
  - harfbuzz=11.3.2
  - icu=75.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libpng=1.6.50
  - libsqlite=3.50.3
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - nextflow=25.04.6
  - openjdk=23.0.2
  - openssl=3.5.1
  - pcre2=10.45
  - pip=25.1.1
  - pixman=0.46.4
  - pthread-stubs=0.4
  - python=3.11.13
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - zstd=1.5.7
  - pip:
    - altair==5.5.0
    - attrs==25.3.0
    - biopython==1.85
    - click==8.2.1
    - contourpy==1.3.3
    - cycler==0.12.1
    - git+https://github.com/kristyhoran/datasmryzr
    - fonttools==4.60.1
    - iniconfig==2.1.0
    - jinja2==3.1.6
    - joblib==1.5.2
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kiwisolver==1.4.9
    - markupsafe==3.0.2
    - matplotlib==3.10.7
    - mycolorpy==1.5.1
    - narwhals==2.4.0
    - numpy==2.3.3
    - packaging==25.0
    - pandas==2.3.2
    - pillow==12.0.0
    - pluggy==1.6.0
    - psutil==7.0.0
    - pygments==2.19.2
    - pyparsing==3.2.5
    - pytest==8.4.2
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - referencing==0.36.2
    - rpds-py==0.27.1
    - scikit-learn==1.7.1
    - scipy==1.16.1
    - six==1.17.0
    - threadpoolctl==3.6.0
    - typing-extensions==4.15.0
    - tzdata==2025.2
