reference:
        "{{reference}}"
min_perc:
        "{{minperc}}"
now:
        "{{now}}"
mask_string:
        "{{mask_string}}"
day:
        "{{day}}"
isolates:
        "{{isolates}}"
gubbins:
        {{gubbins}}
prefill_path:
        "{{prefill_path}}"
pipeline:
        "{{pipeline}}"
workdir:
        "{{workdir}}"
job_id:
        "{{job_id}}"
assembler:
        "{{assembler}}"
template_path:
        "{{template_path}}"
script_path:
        "{{script_path}}"
preview:
        {{preview}}
kraken_db:
        "{{kraken_db}}"
kraken_threads:
        "{{kraken_threads}}"
min_cov:
        {{min_cov}}
# snippy_singularity:
#         "{{snippy_singularity}}"
abritamr_singularity:
        "{{abritamr_singularity}}"
snippy_singularity:
        "{{snippy_singularity}}"