name: BigCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  K2DB: "babykraken"
  K2DB_URL: "https://github.com/MDU-PHL/babykraken/raw/refs/heads/master/dist/babykraken.tar.gz"
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Pull bohra
        uses: actions/checkout@v5

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          miniforge-version: latest
          channels: conda-forge,bioconda
          #conda-remove-defaults: true
          channel-priority: strict
          activate-environment: bohra
          environment-file: BigCI.env.yml
          auto-update-conda: true

      - name: Clean APT
        run: |
          sudo apt clean
          sudo apt autoremove -y
          sudo apt autoclean

      - name: Install Kraken2 database
        run: |
          wget ${K2DB_URL}
          tar zxvf ${K2DB}.tar.gz
          export KRAKEN2_DEFAULT_DB="$PWD/$K2DB"

      - name: Check disk usage
        run: df -h .

      - name: Install bohra
        run: |
          pip3 install .
          bohra install-deps

      - name: Check bohra installtion
        run: |
          bohra check-deps

      - name: Simple bohra test
        run: |
          bohra --version
          bohra --help
          bohra run --help

      - name: Big bohra test
        run: |
          bohra test
