name: BigCI

on:
  push:
    branches: [ master ]
    paths:
      - 'bohra/**'
      - '.github/workflows/BigCI.yml'
      - 'bohra/environments/**'
      - 'pyproject.toml'
      - 'BigCI.env.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'bohra/**'
      - '.github/workflows/BigCI.yml'
      - 'bohra/environments/**'
      - 'pyproject.toml'
      - 'environment.yml'

env:
  K2DB: "babykraken"
  K2DB_URL: "https://github.com/MDU-PHL/babykraken/raw/refs/heads/master/dist/babykraken.tar.gz"
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 32768
          temp-reserve-mb: 16384
          swap-size-mb: 16384
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - name: Pull bohra
        uses: actions/checkout@v5

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          miniforge-version: latest
          channels: conda-forge,bioconda
          #conda-remove-defaults: true
          channel-priority: strict
          activate-environment: bohra
          environment-file: BigCI.env.yml
          auto-update-conda: true

      - name: Clean APT
        run: |
          sudo apt clean
          sudo apt autoremove -y
          sudo apt autoclean

      - name: Check disk usage
        run: df -h

      - name: Install Kraken2 database
        run: |
          wget ${K2DB_URL}
          tar zxvf ${K2DB}.tar.gz
          export KRAKEN2_DEFAULT_DB="$PWD/$K2DB"

      - name: Install bohra
        run: |
          pip3 install .
          bohra deps install

      - name: Check bohra installtion
        run: |
          bohra deps check

      - name: Simple bohra test
        run: |
          bohra --version
          bohra --help
          bohra run --help

      - name: Big bohra test
        run: |
          bohra test
