name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'bohra/**'
      - '.github/workflows/CI.yml'
      - 'bohra/environments/**'
      - 'pyproject.toml'
      - 'environmet.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'bohra/**'
      - '.github/workflows/CI.yml'
      - 'bohra/environments/**'
      - 'pyproject.toml'
      - 'environment.yml'

env:
  K2DB: "babykraken"
  K2DB_URL: "https://github.com/MDU-PHL/babykraken/raw/refs/heads/master/dist/babykraken.tar.gz"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 32768
          temp-reserve-mb: 16384
          swap-size-mb: 16384
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - name: Pull bohra
        uses: actions/checkout@v5

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge,bioconda
          channel-priority: strict
          activate-environment: bohra
          environment-file: environment.yml
          auto-update-conda: true

      - name: Check disk usage
        run: df -h

      - name: Install Kraken2 database
        run: |
          wget ${K2DB_URL}
          tar zxvf ${K2DB}.tar.gz

      - name: Install bohra
        run: |
          pip3 install --no-deps .

      - name: Simple bohra test
        run: |
          bohra --version
          bohra --help
          bohra run --help

      - name: Install bohra deps
        run: |
          bohra deps install

      - name: Check bohra deps
        run: |
          bohra deps check

      - name: Big bohra test
        run: |
          export KRAKEN2_DEFAULT_DB="$PWD/$K2DB"
          bohra test --shovill_ram 8 --cpus 4
