name: sonneitypeCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  K2DB: "babykraken"
  K2DB_URL: "https://github.com/MDU-PHL/babykraken/raw/refs/heads/master/dist/babykraken.tar.gz"
#  "https://github.com/MDU-PHL/babykraken/raw/refs/heads/master/dist/babykraken.tar.gz"
#  KRAKEN2_DEFAULT_DB: "" BOHRA_PUBMLST_DB: "" BOHRA_BLAST_DB: ""
#  BOHRA_MOBSUITE_DB: ""
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Pull bohra
        uses: actions/checkout@v5

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          miniforge-version: latest
          channels: conda-forge,bioconda
          #conda-remove-defaults: true
          channel-priority: strict
          activate-environment: bohra
          environment-file: BigCI.env.yml
          auto-update-conda: true

      - name: Install Kraken2 database
        run: |
          wget ${K2DB_URL}
          tar zxvf ${K2DB}.tar.gz
          export KRAKEN2_DEFAULT_DB="$PWD/$K2DB"
      - name: Check disk usage
        run: |
          echo "Disk space usage:"
          df -h
          echo "Directory space usage:"
          du -sh /home/runner/work /usr /opt 
      - name: Install bohra
        run: |
          pip3 install .
          bohra install-deps --tool sonneitype

      - name: Check bohra installtion
        run: |
          bohra check-deps --tool sonneitype

      - name: Simple bohra test
        run: |
          bohra --version
          bohra --help
          bohra run --help

      # - name: Big bohra test
      #   run: |
      #     bohra test
